services:
  postgres:
    image: postgres:16-alpine
    container_name: drive_postgres
    environment:
      POSTGRES_USER: zbib
      POSTGRES_PASSWORD: zbib
      POSTGRES_DB: drive
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U zbib -d drive" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: drive_minio
    command:
      - server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: zbib
      MINIO_ROOT_PASSWORD: zbib
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/data/minio:/data
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: